
# NFD_FOUND

# NFD_LIBRARIES
# NFD_INCLUDES

# NFD_LIBRARY
# NFD_LIBRARY_RELEASE
# NFD_LIBRARY_DEBUG
# NFD_INCLUDE_DIR

include(FindPackageHandleStandardArgs)

find_path(NFD_INCLUDE_DIR nfd.h
            PATH_SUFFIXES
              NativeFileDialog/include
            REQUIRED)

file(TO_CMAKE_PATH "$ENV{PROGRAMFILES}" ENVPROGRAMFILES)

set(NFD_LIBRARY_HINT ${NFD_INCLUDE_DIR}/../lib)

find_library(NFD_LIBRARY_RELEASE nfd HINTS ${NFD_LIBRARY_HINT} PATH_SUFFIXES nfd/lib lib)
find_library(NFD_LIBRARY_DEBUG nfd HINTS ${NFD_LIBRARY_HINT} PATH_SUFFIXES nfd/lib lib)

if(NFD_LIBRARY_DEBUG AND NFD_LIBRARY_RELEASE)
  set(NFD_LIBRARY "optimized" ${NFD_LIBRARY_RELEASE} "debug" ${NFD_LIBRARY_DEBUG})
elseif(NFD_LIBRARY_RELEASE)
  set(NFD_LIBRARY ${NFD_LIBRARY_RELEASE})
elseif(NFD_LIBRARY_DEBUG)
  set(NFD_LIBRARY ${NFD_LIBRARY_DEBUG})
endif()

set(NFD_INCLUDES ${NFD_INCLUDE_DIR})
set(NFD_LIBRARIES ${NFD_LIBRARY})

find_package_handle_standard_args(NFD DEFAULT_MSG NFD_LIBRARIES NFD_INCLUDES)
